# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: git clone --branch 2.6 --depth 1 https://github.com/jsummers/bmpsuite.git
    - run: cd bmpsuite/ && make clean && make check && cd ../
      env:
        CC: gcc
    - run: ./bin/get-bmpsuite
    - run: node index.js samples/in/bmpsuite/g/*.bmp -d samples/out/bmpsuite/g/ -l log/failed.log
    - run: node index.js samples/in/bmpsuite/q/*.bmp -d samples/out/bmpsuite/q/ -l log/failed.log
    - run: node index.js samples/in/bmpsuite/b/*.bmp -d samples/out/bmpsuite/b/ -l log/failed.log
    - name: Upload the log of failed BMP samples
      uses: actions/upload-artifact@v1
      with:
        name: failed-samples-log
        path: log/failed.log
    - run: ./bin/test
      env:
        CI: true
